mode=test

db.url=jdbc:mysql://knowledge-db.cri3skq2odrs.us-west-2.rds.amazonaws.com:3306/blackbook?autoReconnect=true
db.username=main1
db.password=Player123
db.initialPoolSize=4
db.maxPoolSize=20
db.timeout=10000
db.showsql=false

